import { Inter } from "next/font/google";
import "./globals.css";
import MenuNavBar from "@/components/navigate";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MenuNavBar />
    
        
        {children}</body>
    </html>
  );
}
